name: Deploy to dev

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: [ self-hosted, dev-deploy-runner ]
    environment: develop
    concurrency:
      group: dev-test-deploy
      cancel-in-progress: true

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync repo to dev-test via rsync
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete
          path: ./
          remote_path: /opt/app/MRSPlayground/
          remote_host: ${{ secrets.DEV_TEST_HOST }}
          remote_user: ${{ secrets.DEV_TEST_USER }}
          remote_key:  ${{ secrets.DEV_TEST_SSH_KEY }}

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE_DEV }}" > .env

      - name: Run deploy.sh remotely
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEV_TEST_HOST }}
          username: ${{ secrets.DEV_TEST_USER }}
          key: ${{ secrets.DEV_TEST_SSH_KEY }}
          script: |
            cd /opt/app/MRSPlayground
            ./deploy.sh
