name: Deploy to dev

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: [ self-hosted, dev-deploy-runner ]
    environment: develop
    concurrency:
      group: dev-test-deploy
      cancel-in-progress: true

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: write ssh key
        run: |
          echo "${{ secrets.DEV_TEST_SSH_KEY }}" > /tmp/deploy_key
          chmod 600 /tmp/deploy_key

      - name: Rsync manually
        run: |
          rsync -avzr --delete -e "ssh -i /tmp/deploy_key deploy@${{ secrets.DEV_TEST_HOST }}" ./ ${{ secrets.DEV_TEST_USER }}@${{ secrets.DEV_TEST_HOST }}:/opt/app/MRSPlayground/

      - name: Remove ssh key
        run: rm /tmp/deploy_key

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE_DEV }}" > .env

      - name: Run deploy.sh remotely
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEV_TEST_HOST }}
          username: ${{ secrets.DEV_TEST_USER }}
          key: ${{ secrets.DEV_TEST_SSH_KEY }}
          script: |
            cd /opt/app/MRSPlayground
            ./deploy.sh
