name: Deploy to dev

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: [ self-hosted, dev-deploy-runner ]
    environment: develop
    concurrency:
      group: dev-test-deploy
      cancel-in-progress: true

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: write ssh key
        run: |
          echo "${{ secrets.DEV_TEST_SSH_KEY }}" > /tmp/key
          chmod 600 /tmp/key

      - name: Create .env file
        run: 
          touch .env
          echo "${{ secrets.ENV_FILE_DEV }}" | base64 -d > .env

      - name: nginx permission set
        run: |
          ssh -i /tmp/key ${{ secrets.DEV_TEST_USER }}@${{ secrets.DEV_TEST_HOST }} "sudo mkdir -p /opt/app/MRSPlayground/nginx/logs/ && sudo chown -R deploy:deploy /opt/app/MRSPlayground/nginx/logs/"

      - name: nginx ssl set
        run: |
          ssh -i /tmp/key ${{ secrets.DEV_TEST_USER }}@${{ secrets.DEV_TEST_HOST }} "sudo mkdir -p /opt/app/MRSPlayground/nginx/ssl/ && sudo chown -R deploy:deploy /opt/app/MRSPlayground/nginx/ssl/"
          echo "${{ secrets.DEV_SSL_CERT }}" | base64 -d > /opt/app/MRSPlayground/nginx/ssl/cert.pem
          echo "${{ secrets.DEV_SSL_KEY }}" | base64 -d > /opt/app/MRSPlayground/nginx/ssl/key.pem
          chmod 600 /opt/app/MRSPlayground/nginx/ssl/key.pem
          chmod 644 /opt/app/MRSPlayground/nginx/ssl/cert.pem

      - name: Rsync manually
        run: |
          rsync -avz --delete --exclude='.git' -e "ssh -i /tmp/key" ./ ${{ secrets.DEV_TEST_USER }}@${{ secrets.DEV_TEST_HOST }}:/opt/app/MRSPlayground/

      - name: Run deploy.sh remotely
        run: |
          ssh -i /tmp/key ${{ secrets.DEV_TEST_USER }}@${{ secrets.DEV_TEST_HOST }} "chmod +x /opt/app/MRSPlayground/deploy.sh && cd /opt/app/MRSPlayground && sudo ./deploy.sh"

      - name: Remove ssh key
        run: rm /tmp/key && rm .env
