name: Deploy to dev

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: [ self-hosted, dev-deploy-runner ]
    environment: develop
    concurrency:
      group: dev-test-deploy
      cancel-in-progress: true

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: write ssh key
        run: |
          echo "${{ secrets.DEV_TEST_SSH_KEY }}" > /tmp/key
          chmod 600 /tmp/key

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE_DEV }}" > .env

      - name: Rsync manually
        run: |
          sudo rsync -avz --delete -e "ssh -i /tmp/key" ./ ${{ secrets.DEV_TEST_USER }}@${{ secrets.DEV_TEST_HOST }}:/opt/app/MRSPlayground/

      - name: Run deploy.sh remotely
        run: |
          ssh -i /tmp/key ${{ secrets.DEV_TEST_USER }}@${{ secrets.DEV_TEST_HOST }} "chmod +x /opt/app/MRSPlayground/deploy.sh && cd /opt/app/MRSPlayground && sudo ./deploy.sh"

      - name: Remove ssh key
        run: rm /tmp/key && rm .env
