name: Deploy to dev

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: [ self-hosted, dev-deploy-runner ]
    environment: develop
    concurrency:
      group: dev-test-deploy
      cancel-in-progress: true

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: private key permissions
        run: |
          mkdir -p /tmp/
          echo "${{ secrets.DEV_TEST_SSH_KEY }}" > /tmp/key
          chmod 600 /tmp/key

      - name: nginx permission set
        run: |
          ssh -i /tmp/key ${{ secrets.DEV_TEST_USER }}@${{ secrets.DEV_TEST_HOST }} "sudo mkdir -p /opt/app/MRSPlayground/nginx/logs/ && sudo chown -R deploy:deploy /opt/app/MRSPlayground/nginx/logs/"

      - name: Create or Update SSL Certificates
        run: |
          ssh -T -i /tmp/key ${{ secrets.DEV_TEST_USER }}@${{ secrets.DEV_TEST_HOST }} 'bash -s' <<EOF
            set -e
            
            cd /opt/app/MRSPlayground

            sudo mkdir -p ./nginx/ssl/
            sudo chown -R ${{ secrets.DEV_TEST_USER }}:${{ secrets.DEV_TEST_USER }} ./nginx/ssl/

            printf "%s" "${{ secrets.DEV_SSL_CERT }}" | base64 -d | sudo tee ./nginx/ssl/cert.pem > /dev/null
            printf "%s" "${{ secrets.DEV_SSL_KEY }}" | base64 -d | sudo tee ./nginx/ssl/key.pem > /dev/null

            sudo chmod 644 ./nginx/ssl/cert.pem
            sudo chmod 600 ./nginx/ssl/key.pem
          EOF

      - name: Rsync manually
        run: |
          rsync -avz --delete --exclude='.git' --exclude='.env' --exclude='nginx/ssl' -e "ssh -i /tmp/key" ./ ${{ secrets.DEV_TEST_USER }}@${{ secrets.DEV_TEST_HOST }}:/opt/app/MRSPlayground/

      - name: Create .env file on remote
        run: |
          ssh -i /tmp/key ${{ secrets.DEV_TEST_USER }}@${{ secrets.DEV_TEST_HOST }} 'echo "${{ secrets.ENV_FILE_DEV }}" | base64 -d > /opt/app/MRSPlayground/.env'

      - name: Run deploy.sh remotely
        run: |
          ssh -i /tmp/key ${{ secrets.DEV_TEST_USER }}@${{ secrets.DEV_TEST_HOST }} "chmod +x /opt/app/MRSPlayground/deploy.sh && cd /opt/app/MRSPlayground && sudo ./deploy.sh"

      - name: Remove ssh key
        run: rm /tmp/key
